#!/bin/bash
#===============================================================================
# Modify and merge the .stl files generated by gmsh to remove the tag "Generated
# by Gmsh" and replace it with the patch name

# EFFECTS/INFO
#   The patch name is the local filename without extension
#   The merged filename is "domain_merged.stl" within the geometry folder
#   The merged file is copied up one level to the case root directory, to be used
#   in meshing
#===============================================================================

angle=$1
read_path="${AHMED_SLANT_PATH}/slant_angle_${angle}/geometry/"
check_path="${read_path}*.stl"
fn_merged="${read_path}domain_merged.stl"
rm $fn_merged
fn_merged_copy="${AHMED_SLANT_PATH}/slant_angle_${angle}/domain_merged.stl"
gmsh_tag="Created by Gmsh"

for curstl in $check_path
do
    #get the patch name by stripping extension and path from filename
    patch_name=$(basename -s .stl "$curstl")
    echo $patch_name
    
    #replace the gmsh tag in the stl file with the patch name
    sed -i -e "s/${gmsh_tag}/${patch_name}/g" $curstl

    #merge all stl's into single file
    cat $curstl >> $fn_merged
done

cp $fn_merged $fn_merged_copy
